version: 2
sources:
  - name: raw
   schema: gz_raw_data
tables:
  Generate model

  - name: sales
    identifier: raw_gz_sales
    Generate model
    - name: product
    identifier: raw_gz_product
      Generate model
      - name: ship
    identifier: raw_gz_ship